-- Run in a disposable database after baseline.sql and 001_v3.sql. Fail on first error.
DO $$
DECLARE first uuid; second uuid; op uuid:=gen_random_uuid(); result jsonb; replay jsonb; event uuid:=gen_random_uuid(); count_rows integer;
BEGIN
 result:=public.fb_lfg('create','Alice','{"activity":"YAMA","capacity":2}',op);
 IF result->>'status'<>'ok' THEN RAISE EXCEPTION 'create: %',result; END IF;
 first:=(result->>'id')::uuid;
 replay:=public.fb_lfg('create','Alice','{"activity":"YAMA","capacity":2}',op);
 IF replay<>result THEN RAISE EXCEPTION 'non-idempotent create'; END IF;
 IF public.fb_lfg('create','Bob','{"activity":"YAMA","capacity":2}',op)->>'status'<>'conflict' THEN RAISE EXCEPTION 'operation collision accepted'; END IF;
 result:=public.fb_lfg('create','Charlie','{"activity":"YAMA","capacity":2}',gen_random_uuid());
 second:=(result->>'id')::uuid;
 result:=public.fb_lfg('apply','Bob',jsonb_build_object('id',first),gen_random_uuid());
 IF result->>'status'<>'ok' THEN RAISE EXCEPTION 'apply: %',result; END IF;
 result:=public.fb_lfg('apply','Bob',jsonb_build_object('id',gen_random_uuid()),gen_random_uuid());
 IF result->>'status'<>'not_found' OR NOT EXISTS(SELECT 1 FROM public.lfg_applicants WHERE party_id=first AND rsn='bob') THEN RAISE EXCEPTION 'failed switch lost application'; END IF;
 result:=public.fb_lfg('accept','Alice',jsonb_build_object('id',first,'rsn','Bob'),gen_random_uuid(),1);
 IF result->>'status'<>'conflict' THEN RAISE EXCEPTION 'stale version accepted'; END IF;
 op:=gen_random_uuid();
 result:=public.fb_lfg('accept','Alice',jsonb_build_object('id',first,'rsn','Bob'),op,2);
 IF result->>'status'<>'ok' OR result->>'formed_id' IS NULL THEN RAISE EXCEPTION 'formation: %',result; END IF;
 IF EXISTS(SELECT 1 FROM public.lfg_parties WHERE id=first) THEN RAISE EXCEPTION 'formed party still live'; END IF;
 replay:=public.fb_lfg('accept','Alice',jsonb_build_object('id',first,'rsn','Bob'),op,2);
 IF replay<>result OR (SELECT count(*) FROM public.lfg_formed_parties WHERE party_id=first)<>1 THEN RAISE EXCEPTION 'duplicate formation'; END IF;
 result:=public.fb_lfg('create','Dave','{"activity":"TOB","capacity":3,"host_role":"COX_FILL"}',gen_random_uuid());
 IF result->>'status'<>'invalid' THEN RAISE EXCEPTION 'cross-mode host accepted'; END IF;
 result:=public.fb_lfg('create','Dave','{"activity":"TOB","capacity":4,"host_role":"TOB_MELEE"}',gen_random_uuid());
 IF result->>'status'<>'ok' THEN RAISE EXCEPTION 'role party: %',result; END IF;
 first:=(result->>'id')::uuid;
 result:=public.fb_lfg('apply','Eve',jsonb_build_object('id',first,'role','TOB_HM_FILL'),gen_random_uuid());
 IF result->>'status'<>'invalid' THEN RAISE EXCEPTION 'cross-mode wildcard accepted'; END IF;
 result:=public.fb_lfg('apply','Eve',jsonb_build_object('id',first,'role','TOB_FRZ'),gen_random_uuid());
 IF result->>'status'<>'ok' THEN RAISE EXCEPTION 'generic freeze apply: %',result; END IF;
 result:=public.fb_lfg('accept','Dave',jsonb_build_object('id',first,'rsn','Eve'),gen_random_uuid());
 IF result->>'status'<>'ok' OR (SELECT role FROM public.lfg_applicants WHERE party_id=first AND rsn='eve')<>'TOB_NFRZ' THEN RAISE EXCEPTION 'freeze assignment: %',result; END IF;
 result:=public.fb_lfg('apply','Eve',jsonb_build_object('id',second),gen_random_uuid());
 IF result->>'status'<>'invalid' OR NOT EXISTS(SELECT 1 FROM public.lfg_applicants WHERE party_id=first AND rsn='eve' AND status='ACCEPTED') THEN RAISE EXCEPTION 'accepted member switched silently'; END IF;
 result:=public.fb_submit_pbs(' Alice ','[{"boss_key":"vorkath","seconds":70,"source":"live"},{"boss_key":"bad","seconds":"NaN","source":"seed"},{"boss_key":"zulrah","seconds":50,"source":"seed"}]');
 IF result->>'accepted'<>'2' OR result->>'rejected'<>'1' THEN RAISE EXCEPTION 'partial PB: %',result; END IF;
 PERFORM public.fb_submit_pbs('ALICE','[{"boss_key":"vorkath","seconds":90,"source":"seed"}]');
 IF (SELECT seconds FROM public.personal_bests WHERE rsn='alice' AND boss_key='vorkath')<>70 THEN RAISE EXCEPTION 'PB worsened'; END IF;
 PERFORM public.fb_submit_stats('Alice',100,1500,1000,'Elite');
 PERFORM public.fb_submit_stats('ALICE',100,1600,1000,'Master');
 IF NOT EXISTS(SELECT 1 FROM public.member_stats WHERE rsn='alice' AND cl_total=1600 AND ca_tier='Master') THEN RAISE EXCEPTION 'same-count metadata not updated'; END IF;
 result:=public.fb_submit_drop(jsonb_build_object('event_id',event,'rsn','Alice','npc_name','Nex','item_name','Torva','item_id',1,'quantity',10,'ge_value',5000000000,'world_type','standard','occurred_at',now()));
 IF result->>'status'<>'ok' THEN RAISE EXCEPTION 'large drop: %',result; END IF;
 PERFORM public.fb_submit_drop(jsonb_build_object('event_id',event,'rsn','Alice','npc_name','Nex','item_name','Torva','item_id',1,'quantity',10,'ge_value',5000000000,'world_type','standard','occurred_at',now()));
 IF (SELECT count(*) FROM public.drops WHERE event_id=event)<>1 THEN RAISE EXCEPTION 'duplicate drop'; END IF;
 PERFORM public.fb_submit_drop(jsonb_build_object('event_id',gen_random_uuid(),'rsn','Alice','npc_name','Nex','item_name','Torva','item_id',1,'quantity',1,'ge_value',100,'world_type','special','occurred_at',now()));
 IF (SELECT total_gp FROM public.gp_week_total)<>5000000000 THEN RAISE EXCEPTION 'special world in GP total'; END IF;
 FOR count_rows IN 1..25 LOOP PERFORM public.fb_submit_stats('member'||count_rows,NULL,NULL,2000,'Elite'); END LOOP;
 IF (SELECT count(*) FROM public.member_badges)<26 THEN RAISE EXCEPTION 'badges limited to twenty'; END IF;
 IF public.fb_board()->>'protocol'<>'3' THEN RAISE EXCEPTION 'board protocol'; END IF;
 IF has_table_privilege('anon','public.drops','INSERT') OR has_function_privilege('anon','public.submit_pbs(text,jsonb)','EXECUTE') OR has_function_privilege('anon','public.fb_cleanup()','EXECUTE') THEN RAISE EXCEPTION 'mutation bypass grant'; END IF;
END $$;
SET ROLE anon;
DO $$ BEGIN
 IF public.fb_board()->>'protocol'<>'3' THEN RAISE EXCEPTION 'anon board'; END IF;
 IF public.fb_submit_stats('AnonTester',1,1500,NULL,NULL)->>'status'<>'ok' THEN RAISE EXCEPTION 'anon stats'; END IF;
 BEGIN
  DELETE FROM public.lfg_parties;
  RAISE EXCEPTION 'anon direct delete succeeded';
 EXCEPTION WHEN insufficient_privilege THEN NULL; END;
END $$;
RESET ROLE;
