displayName=Final Boss
author=shok
support=https://github.com/orgonag/fbclan-plugin
description=Clan tools for Final Boss - drop logging, LFG, and more
tags=clan,final boss,drops,lfg,looking for group
plugins=com.github.orgonag.fbclan.FinalBossPlugin
build=standard
